### ISSUE TITLE
"_JAVA_AWT_WM_NONREPARENTING=1" offsetting cursor

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.github.reds.LogisimEvolution#2]
@tinywrkb adding the variable `_JAVA_AWT_WM_NONREPARENTING=1`, as mentioned at https://github.com/flathub/flathub/pull/1951#issuecomment-735912173, I noticed that my cursor offsets:

![offset](https://user-images.githubusercontent.com/50847364/101042460-3ac8f580-354b-11eb-8d9c-5cf6dfe0fb10.gif)

Removing `_JAVA_AWT_WM_NONREPARENTING=1` fixes the offset.

Do you think we should remove that variable? You said that it is fixed in JRE 15 https://github.com/flathub/flathub/pull/1951#issuecomment-735977952, I think it would be wise to remove it altogether.

**Comment by tinywrkb** [comment]
Argh... I was pretty sure it was fixed, might had a typo when tested.  
Anyway, if this causes trouble on Gnome then just drop it, wlroots' users aware that they need workarounds to get some things working smoothly.

**Comment by TheEvilSkeleton** [comment]
Alright, I'll make sure to add the variable in the README.
